name: NBA-referees-analysis
channels:
- conda-forge
- defaults
- anaconda
dependencies:
- python>=3.8
- jupyter
- jupyterlab>=3.0
- pymc3
- pip
- seaborn
- matplotlib
- numpy
- scipy
- pandas
- tqdm
- missingno
- scikit-learn
- nodejs
- pyjanitor
- xarray
- pandoc
- black
- nbstripout
- pylint
- arviz
- theano
- ipykernel
- hvplot
- bokeh
- holoviews
- mkl
- mkl-service
- pre-commit
- networkx
- mamba  #fast conda env solver
- pyprojroot
- faker
- lxml
- python-graphviz
- pip:
  - mkdocs
  - mkdocs-material
  - mknotebooks
  - daft
  # Need to add pip install from github for repo, so solutions can be executed.
